### ISSUE TITLE
Preparing for 1.0.0

### ISSUE THREAD

**Issue by benpueschel** [benpueschel/gritty#2]
# TODO
- [x] Unify (and simplify) secrets storage configuration (018f00f)
- [x] Generate man-pages (using [clap_mangen](https://crates.io/crates/clap_mangen))
  - [x] More extensive documentation (a7a5b48)
  - [x] Maybe break documentation up into separate modules? (a8edce0)
- [x] Add a `--format` option to specify a machine-friendly output format (e.g. `json`) (f9959b4)
- [x] Add a better [panic handler](https://crates.io/crates/human-panic) for the end-user - `thread 'main' panicked at 'example_fn', src/main.rs:96:240` isn't a very descriptive message for the average user (ee84498)
- [x] Actually implement Windows support
  - [x] Use `std::fs::Path` (41cc53f)
  - [x] Change config directory to `%LOCALAPPDATA%` (god I hate Windows env vars) on Windows, because `~/.config` obviously does not exist (4e94c08)

**Comment by benpueschel** [comment]
All done
